/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

import java.util.Scanner;

public class App {
    public String getGreeting(String name) {
        String sayHello = (name == null || name.equals("")) ? "Hello World!" : "Hello "+name;
        return sayHello;
    }

    public static void main(String[] args) {
    
		Scanner input = new Scanner(System.in);
		
		// leggo un ID del client
		System.out.println("Inserisci nome: ");
		String name = input.nextLine();
		
        System.out.println(new App().getGreeting(name));
    }
}
